name: Build Arch Package

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: archlinux:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Arch
        run: pacman -Syu --noconfirm

      - name: Install build tools
        run: |
          pacman -S --noconfirm \
            base-devel \
            git

      - name: Check environment
        run: |
          uname -a
          pacman --version
          makepkg --version
