name: Build Arch Package

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: archlinux:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Arch
        run: pacman -Syu --noconfirm

      - name: Install build tools
        run: |
          pacman -S --noconfirm \
            base-devel \
            git
      - name: Get Arch libfprint PKGBUILD
        run: |
          git clone https://gitlab.archlinux.org/archlinux/packaging/packages/libfprint.git arch-libfprint
          ls -la arch-libfprint
      - name: Show PKGBUILD
        run: |
          cat arch-libfprint/PKGBUILD

      - name: Copy NB2033 patch
        run: |
          cp nb2033u.patch arch-libfprint/
          ls -l arch-libfprint/nb2033u.patch

      - name: Check environment
        run: |
          uname -a
          pacman --version
          makepkg --version
